FROM postgres:18-alpine

COPY ./schema/production.sql /docker-entrypoint-initdb.d/01-init.sql
COPY ./init/runcodes-password.sh /docker-entrypoint-initdb.d/02-init.sh
RUN chmod +x /docker-entrypoint-initdb.d/02-init.sh
